name: tabler_sass.dart
version: 0.0.32
description: Tabler sass source files to create dart web apps with
author: devkabiir <dev@kabiir.me>
homepage: https://github.com/devkabiir/tabler_sass.dart

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dependencies:
  bootstrap_sass: ^4.1.2

dev_dependencies:
  sass_builder: ^2.1.1
  build_runner: any
  build_test: any
  build_web_compilers: any
